export const BIKE_BOOKED_ACTION = 'BIKE_BOOKED_ACTION';
export const BIKE_RETURNED_ACTION = 'BIKE_RETURNED_ACTION';

// Bike booking request
export const BOOK_BIKE_REQUEST = {
  START: 'BOOK_BIKE_REQUEST_START',
  SUCCESS: 'BOOK_BIKE_REQUEST_SUCCESS',
  FAILURE: 'BOOK_BIKE_REQUEST_FAILUE',
};
