// Get stations request
export const GET_STATIONS_REQUEST = {
  START: 'GET_STATIONS_REQUEST_START',
  SUCCESS: 'GET_STATIONS_REQUEST_SUCCESS',
  FAILURE: 'GET_STATIONS_REQUEST_FAILURE',
};

// Get stations request
export const GET_STATION_BIKES_REQUEST = {
  START: 'GET_STATION_BIKES_REQUEST_START',
  SUCCESS: 'GET_STATION_BIKES_REQUEST_SUCCESS',
  FAILURE: 'GET_STATION_BIKES_REQUEST_FAILURE',
};

// Bike booking request
export const BOOK_BIKE_REQUEST = {
  START: 'BOOK_BIKE_REQUEST_START',
  SUCCESS: 'BOOK_BIKE_REQUEST_SUCCESS',
  FAILURE: 'BOOK_BIKE_REQUEST_FAILURE',
};

// Bike return request
export const BIKE_RETURNED_ACTION = 'BIKE_RETURNED_ACTION';
